---
# Variables por defecto para el rol mariadb
mariadb_packages:
  - mariadb-server
  - python3-pymysql

# Configuración de servicio
mariadb_service_name: mariadb

# Base de datos y usuario de la aplicación
db_name: wordpress_db
db_user: wp_user
db_password: wp_secure_password_123
db_host: localhost

# Endurecimiento de seguridad
mariadb_remove_anonymous_users: true
mariadb_remove_test_database: true
